'use client';
import { useState } from 'react';
import { Users, Copy, Check } from 'lucide-react';
import { Button, DatePicker } from '@/components/ui';
import { useAuth } from '@/features/auth/auth-context';
import { useCurrency } from '@/features/preferences/hooks';
import { money } from '@/lib/format';
import { useHouseholds, useHouseholdAction } from '../hooks';
export function Household() {
  const query=useHouseholds(), action=useHouseholdAction(), {user}=useAuth(), currency=useCurrency();
  const [selected,setSelected]=useState(''),[name,setName]=useState(''),[code,setCode]=useState(''),[invite,setInvite]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
  const [expense,setExpense]=useState({name:'',amount:'',dueDate:'',payerId:''});
  const household=query.data?.find(item=>item.id===selected)||query.data?.[0];
  async function run(input:Record<string,unknown>) {setError('');setNotice('');try{const result=await action.mutateAsync(input);if(result.inviteCode)setInvite(result.inviteCode);else setNotice('Saved. Everyone in the household will see the update.');return true;}catch(error){setError(error instanceof Error?error.message:'Could not save');return false;}}
  if(query.isLoading)return <p role="status">Opening your household…</p>;
  if(query.isError)return <p role="alert">Could not load households. <button className="underline" onClick={()=>void query.refetch()}>Try again</button></p>;
  return <div className="space-y-6"><div className="studio-card"><div className="flex gap-4 items-start"><Users size={30}/><div><p className="eyebrow">A HOME FOR SHARED COSTS</p><h2 className="studio-title mt-2">Together, without the awkward maths.</h2><p className="text-sm text-muted mt-3">Split costs equally, choose who pays, and keep track of reimbursements. Household entries are separate from personal bills.</p></div></div><div className="grid md:grid-cols-2 gap-5 mt-6"><form onSubmit={async event=>{event.preventDefault();if(await run({action:'create',name}))setName('');}} className="flex gap-2 items-end"><label className="studio-label flex-1">New household<input required maxLength={80} value={name} onChange={event=>setName(event.target.value)} placeholder="Our little home"/></label><Button type="submit" disabled={action.isPending}>Create</Button></form><form onSubmit={async event=>{event.preventDefault();if(await run({action:'join',code}))setCode('');}} className="flex gap-2 items-end"><label className="studio-label flex-1">Have an invite?<input required value={code} onChange={event=>setCode(event.target.value)} placeholder="Paste invitation code"/></label><Button variant="outline" type="submit" disabled={action.isPending}>Join</Button></form></div><p className="text-xs text-muted mt-3">Joining shares your name and email with members. Personal bills, cards, and statements stay private. Use one agreed currency: {currency}.</p></div>
    {error&&<p role="alert" className="studio-error">{error}</p>}{notice&&<p role="status" className="studio-verdict">{notice}</p>}
    {household&&<><div className="flex flex-wrap gap-4 justify-between items-center"><label className="studio-label">Your household<select value={household.id} onChange={event=>{setSelected(event.target.value);setInvite('');setExpense({name:'',amount:'',dueDate:'',payerId:''});}}>{query.data?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{household.members.some(member=>member.userId===user?.sub&&member.role==='owner')&&<Button variant="outline" disabled={action.isPending} onClick={()=>void run({action:'invite',householdId:household.id})}>Create invitation code</Button>}</div>
      {invite&&<div className="studio-card"><p className="text-sm mb-3">Share this code privately. It expires in seven days. Creating another code replaces it.</p><div className="flex flex-wrap gap-3 items-center"><code className="break-all select-all">{invite}</code><Button size="sm" variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(invite);setNotice('Invitation code copied.');}catch{setError('Copy the code shown above.');}}}><Copy size={15}/>Copy</Button></div></div>}
      <div className="grid lg:grid-cols-[1fr_1.5fr] gap-6"><form className="studio-card space-y-4" onSubmit={async event=>{event.preventDefault();if(await run({action:'expense',householdId:household.id,...expense,amount:Number(expense.amount),payerId:expense.payerId||user?.sub}))setExpense({name:'',amount:'',dueDate:'',payerId:''});}}><h3 className="studio-title">Split a bill.</h3><label className="studio-label">What’s it for?<input required maxLength={120} value={expense.name} onChange={event=>setExpense({...expense,name:event.target.value})}/></label><label className="studio-label">Total ({currency})<input type="number" min="0.01" max="999999999" step="0.01" required value={expense.amount} onChange={event=>setExpense({...expense,amount:event.target.value})}/></label><label className="studio-label">Due date<DatePicker label="Shared bill due date" required id="household-due" value={expense.dueDate} onChange={value=>setExpense({...expense,dueDate:value})}/></label><label className="studio-label">Who pays the provider?<select value={expense.payerId||user?.sub} onChange={event=>setExpense({...expense,payerId:event.target.value})}>{household.members.map(member=><option key={member.userId} value={member.userId}>{member.user.name||member.user.email}</option>)}</select></label><p className="text-sm text-muted">Split equally between {household.members.length} current members. Any spare cent is assigned consistently.</p><Button disabled={action.isPending} type="submit">Add shared bill</Button></form>
      <div className="space-y-4">{household.expenses.length===0?<div className="studio-card text-center py-12"><Users className="mx-auto mb-4"/><p>No shared bills yet. Your first split starts here.</p></div>:household.expenses.map(item=><article className="studio-card" key={item.id}><div className="flex justify-between gap-3"><div><h3 className="text-lg font-semibold">{item.name}</h3><p className="text-xs text-muted mt-1">Due {item.dueDate.slice(0,10)} · {item.paid?'Provider paid':'Awaiting payment'}</p></div><strong>{money(item.amount,currency)}</strong></div><p className="text-sm mt-3">Payer: {household.members.find(member=>member.userId===item.payerId)?.user.name||'Former member'}</p>{!item.paid&&item.payerId===user?.sub&&<Button className="mt-3" size="sm" disabled={action.isPending} onClick={()=>void run({action:'paid',householdId:household.id,expenseId:item.id})}>Record provider payment</Button>}<div className="mt-4 border-t border-line">{item.shares.map(share=><div className="flex flex-wrap justify-between gap-2 py-3 text-sm border-b border-line" key={share.userId}><span>{household.members.find(member=>member.userId===share.userId)?.user.name||'Former member'} · {money(share.amount,currency)}</span>{share.userId===item.payerId?<span className="text-muted">Payer’s share</span>:share.settled?<span className="flex gap-1 items-center"><Check size={14}/>Reimbursed</span>:item.paid&&item.payerId===user?.sub?<button className="underline" disabled={action.isPending} onClick={()=>void run({action:'settle',householdId:household.id,expenseId:item.id,memberId:share.userId})}>Confirm received</button>:<span className="text-muted">{item.paid?'Owed to payer':'Due after payment'}</span>}</div>)}</div></article>)}</div></div></>}
  </div>;
}
