'use client';
import { useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, Download } from 'lucide-react';
import { format, parseISO } from 'date-fns';
import { Mascot } from '@/components/mascot';
import { Button } from '@/components/ui';
import { useCurrency } from '@/features/preferences/hooks';
import type { Bill } from '@/features/bills/types';
import type { CreditCard } from '@/features/cards/types';
import { money } from '@/lib/format';
import type { StatementRow } from '../types';
export function MonthlyStory({bills,cards,transactions}:{bills:Bill[];cards:CreditCard[];transactions:StatementRow[]}) {
  const [month,setMonth]=useState(format(new Date(),'yyyy-MM')),[slide,setSlide]=useState(0),touch=useRef(0),currency=useCurrency();
  const paid=bills.filter(bill=>bill.status==='PAID'&&bill.paymentDate?.slice(0,7)===month),due=bills.filter(bill=>bill.dueDate.slice(0,7)===month);
  const total=paid.reduce((sum,bill)=>sum+(bill.paidAmount||bill.amount),0),spending=transactions.filter(row=>row.date.startsWith(month)&&row.amount>0).reduce((sum,row)=>sum+row.amount,0);
  const unpaid=due.filter(bill=>bill.status!=='PAID');
  const slides=[{eyebrow:'YOUR MONTH, IN A MOMENT',title:paid.length?'Look at you, showing up.':'Every small start counts.',value:`${paid.length}`,detail:'bills recorded as paid this month',note:'A little less on your plate. A little more room for life.'},{eyebrow:'THE THINGS YOU TOOK CARE OF',title:'One less thing to think about.',value:money(total,currency),detail:'in recorded bill payments',note:paid.map(bill=>bill.name).slice(0,4).join(' · ')||'Record a bill payment to start your story.'},{eyebrow:'THE EVERYDAY PICTURE',title:'Small spends tell a story.',value:money(spending,currency),detail:'spending in imported statement rows',note:`${cards.length} cards tracked today. Imported spending may overlap bill payments; these totals are not added together.`},{eyebrow:'A LITTLE LOOK AHEAD',title:unpaid.length?'Your next chapter is waiting.':'A calmer finish.',value:`${unpaid.length}`,detail:'unpaid bills due in this month',note:unpaid.length?`Next up: ${unpaid.sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0].name}.`:'No unpaid bills recorded for this month. Nice work.'}];
  const story=slides[slide];
  function download() {const text=`PocketMATE • ${month}\n\n`+slides.map(item=>`${item.title}\n${item.value} ${item.detail}\n${item.note}`).join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const link=document.createElement('a');link.href=url;link.download=`pocketmate-story-${month}.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <div className="max-w-3xl mx-auto"><div className="flex flex-wrap gap-4 justify-between items-end mb-5"><label className="studio-label">Choose your month<input type="month" required value={month} onChange={event=>{if(event.target.value){setMonth(event.target.value);setSlide(0);}}}/></label><Button variant="outline" onClick={download}><Download size={16}/>Save recap</Button></div><section className="studio-story" tabIndex={0} aria-label="Monthly recap" onKeyDown={event=>{if(event.key==='ArrowRight')setSlide(Math.min(3,slide+1));if(event.key==='ArrowLeft')setSlide(Math.max(0,slide-1));}} onTouchStart={event=>{touch.current=event.changedTouches[0].clientX;}} onTouchEnd={event=>{const delta=event.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>50)setSlide(Math.max(0,Math.min(3,slide+(delta<0?1:-1))));}}><div className="studio-story-progress">{slides.map((_,i)=><button key={i} aria-label={`Show recap page ${i+1}`} aria-current={i===slide?'step':undefined} onClick={()=>setSlide(i)} className={i<=slide?'is-filled':''}/>)}</div><p className="eyebrow">{format(parseISO(`${month}-01`),'MMMM yyyy')} / {story.eyebrow}</p><div aria-live="polite"><h2>{story.title}</h2><strong className="studio-story-value">{story.value}</strong><p className="text-lg">{story.detail}</p><p className="text-sm max-w-md mt-5 opacity-80">{story.note}</p></div><Mascot className="studio-story-mascot"/><div className="flex justify-between items-center mt-8 relative z-10"><button className="studio-story-arrow" aria-label="Previous recap page" disabled={slide===0} onClick={()=>setSlide(slide-1)}><ChevronLeft/></button><span className="text-xs">{slide+1} / 4 · swipe or use arrow keys</span><button className="studio-story-arrow" aria-label="Next recap page" disabled={slide===3} onClick={()=>setSlide(slide+1)}><ChevronRight/></button></div></section></div>;
}
